/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards/$dashboardId'
import { Route as DashboardsDashboardIdIndexRouteImport } from './routes/dashboards/$dashboardId.index'
import { Route as DashboardsDashboardIdEditRouteImport } from './routes/dashboards/$dashboardId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdIndexRoute =
  DashboardsDashboardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)
const DashboardsDashboardIdEditRoute =
  DashboardsDashboardIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/': typeof DashboardsDashboardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/dashboards/$dashboardId/': typeof DashboardsDashboardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards/$dashboardId'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboards/$dashboardId/edit' | '/dashboards/$dashboardId'
  id:
    | '__root__'
    | '/'
    | '/dashboards/$dashboardId'
    | '/dashboards/$dashboardId/edit'
    | '/dashboards/$dashboardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId/': {
      id: '/dashboards/$dashboardId/'
      path: '/'
      fullPath: '/dashboards/$dashboardId/'
      preLoaderRoute: typeof DashboardsDashboardIdIndexRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
    '/dashboards/$dashboardId/edit': {
      id: '/dashboards/$dashboardId/edit'
      path: '/edit'
      fullPath: '/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof DashboardsDashboardIdEditRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
  }
}

interface DashboardsDashboardIdRouteChildren {
  DashboardsDashboardIdEditRoute: typeof DashboardsDashboardIdEditRoute
  DashboardsDashboardIdIndexRoute: typeof DashboardsDashboardIdIndexRoute
}

const DashboardsDashboardIdRouteChildren: DashboardsDashboardIdRouteChildren = {
  DashboardsDashboardIdEditRoute: DashboardsDashboardIdEditRoute,
  DashboardsDashboardIdIndexRoute: DashboardsDashboardIdIndexRoute,
}

const DashboardsDashboardIdRouteWithChildren =
  DashboardsDashboardIdRoute._addFileChildren(
    DashboardsDashboardIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
